# --- dataset generation ---
n_lines: 1000
filter_nouns: true
use_transitive_closure: false
head: true
# --- training settings ---
dim: 3
epochs: 200
baseLR: 0.05
negK: 10
burnC: 0.1
burnEpochs: 10
batchSize: 256
