# --- dataset generation ---
n_lines: 150
filter_nouns: true
use_transitive_closure: true

# --- training settings ---
dim: 5
epochs: 100
baseLR: 0.05
negK: 10
burnC: 0.1
burnEpochs: 10
batchSize: 256
